export const CONFIRMATION_ACTION_TYPES = {
    DELETE_PAYOUT_ACCOUNT: 'DELETE_PAYOUT_ACCOUNT',
    DELETE_EVENT: 'DELETE_EVENT',
    PUBLISH_EVENT: 'PUBLISH_EVENT',
    UNPUBLISH_EVENT: 'UNPUBLISH_EVENT',
    BULK_DELETE_EVENTS: 'BULK_DELETE_EVENTS',
    BULK_CANCEL_EVENTS: 'BULK_CANCEL_EVENTS',
    BULK_UNPUBLISH_EVENTS: 'BULK_UNPUBLISH_EVENTS',
} as const

export type ConfirmationActionType = keyof typeof CONFIRMATION_ACTION_TYPES